[2025-08-06T19:52:31.297+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: local_kafka_to_delta_pipeline.process_kafka_data_locally manual__2025-08-06T19:52:30.725209+00:00 [queued]>
[2025-08-06T19:52:31.306+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: local_kafka_to_delta_pipeline.process_kafka_data_locally manual__2025-08-06T19:52:30.725209+00:00 [queued]>
[2025-08-06T19:52:31.307+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2025-08-06T19:52:31.325+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): process_kafka_data_locally> on 2025-08-06 19:52:30.725209+00:00
[2025-08-06T19:52:31.331+0000] {standard_task_runner.py:60} INFO - Started process 205 to run task
[2025-08-06T19:52:31.333+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'local_kafka_to_delta_pipeline', 'process_kafka_data_locally', 'manual__2025-08-06T19:52:30.725209+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/local_pipeline_dag.py', '--cfg-path', '/tmp/tmp3w7f29aw']
[2025-08-06T19:52:31.335+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask process_kafka_data_locally
[2025-08-06T19:52:31.381+0000] {task_command.py:423} INFO - Running <TaskInstance: local_kafka_to_delta_pipeline.process_kafka_data_locally manual__2025-08-06T19:52:30.725209+00:00 [running]> on host 18af08a535de
[2025-08-06T19:52:31.460+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='local_kafka_to_delta_pipeline' AIRFLOW_CTX_TASK_ID='process_kafka_data_locally' AIRFLOW_CTX_EXECUTION_DATE='2025-08-06T19:52:30.725209+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-06T19:52:30.725209+00:00'
[2025-08-06T19:52:31.461+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-06T19:52:31.461+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        docker exec --user spark har_project-spark-master-1 /opt/spark/bin/spark-submit         --master spark://spark-master:7077         /opt/spark/work-dir/jobs/process_kafka_to_local.py\n        ']
[2025-08-06T19:52:31.470+0000] {subprocess.py:86} INFO - Output:
[2025-08-06T19:52:31.484+0000] {subprocess.py:93} INFO - Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[2025-08-06T19:52:31.486+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-06T19:52:31.496+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-06T19:52:31.500+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=local_kafka_to_delta_pipeline, task_id=process_kafka_data_locally, execution_date=20250806T195230, start_date=20250806T195231, end_date=20250806T195231
[2025-08-06T19:52:31.513+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 3 for task process_kafka_data_locally (Bash command failed. The command returned a non-zero exit code 1.; 205)
[2025-08-06T19:52:31.545+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-06T19:52:31.564+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
