[2025-08-06T19:53:01.479+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: local_kafka_to_delta_pipeline.process_kafka_data_locally manual__2025-08-06T19:53:00.774092+00:00 [queued]>
[2025-08-06T19:53:01.489+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: local_kafka_to_delta_pipeline.process_kafka_data_locally manual__2025-08-06T19:53:00.774092+00:00 [queued]>
[2025-08-06T19:53:01.489+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2025-08-06T19:53:01.504+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): process_kafka_data_locally> on 2025-08-06 19:53:00.774092+00:00
[2025-08-06T19:53:01.510+0000] {standard_task_runner.py:60} INFO - Started process 234 to run task
[2025-08-06T19:53:01.514+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'local_kafka_to_delta_pipeline', 'process_kafka_data_locally', 'manual__2025-08-06T19:53:00.774092+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/local_pipeline_dag.py', '--cfg-path', '/tmp/tmp4ahrus4b']
[2025-08-06T19:53:01.516+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask process_kafka_data_locally
[2025-08-06T19:53:01.563+0000] {task_command.py:423} INFO - Running <TaskInstance: local_kafka_to_delta_pipeline.process_kafka_data_locally manual__2025-08-06T19:53:00.774092+00:00 [running]> on host 18af08a535de
[2025-08-06T19:53:01.643+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='local_kafka_to_delta_pipeline' AIRFLOW_CTX_TASK_ID='process_kafka_data_locally' AIRFLOW_CTX_EXECUTION_DATE='2025-08-06T19:53:00.774092+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-06T19:53:00.774092+00:00'
[2025-08-06T19:53:01.644+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-06T19:53:01.645+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        docker exec --user spark har_project-spark-master-1 /opt/spark/bin/spark-submit         --master spark://spark-master:7077         /opt/spark/work-dir/jobs/process_kafka_to_local.py\n        ']
[2025-08-06T19:53:01.654+0000] {subprocess.py:86} INFO - Output:
[2025-08-06T19:53:01.668+0000] {subprocess.py:93} INFO - Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[2025-08-06T19:53:01.669+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-06T19:53:01.681+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-06T19:53:01.686+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=local_kafka_to_delta_pipeline, task_id=process_kafka_data_locally, execution_date=20250806T195300, start_date=20250806T195301, end_date=20250806T195301
[2025-08-06T19:53:01.698+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 5 for task process_kafka_data_locally (Bash command failed. The command returned a non-zero exit code 1.; 234)
[2025-08-06T19:53:01.725+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-06T19:53:01.743+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
